# Numpy

Numerical Python. We can use C code optimizations while writing Python. 

In [2]:
import numpy as np

## Datatypes and Attributes

Numpy's main data type is ndarray

In [5]:
a1 = np.array([1, 2, 3])
type(a1)

numpy.ndarray

In [8]:

a2 = np.array([[1, 2, 3],[4, 5, 6]])    # 2D array
a3 = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]], [[10, 11, 12],[13, 14, 15],[16, 17, 18]]])  # 3D array
a3.shape

(2, 3, 3)

In [12]:
a3.ndim, a3.shape, a3.size

(3, (2, 3, 3), 18)

In [13]:
a3.dtype

dtype('int32')

## Creating Arrays

In [23]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [14]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
ones.dtype

dtype('float64')

In [17]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
range_array = np.arange(0,10,3)
range_array

array([0, 3, 6, 9])

In [20]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[9, 1, 3, 5, 8],
       [2, 9, 5, 8, 5],
       [7, 9, 6, 2, 7]])

In [21]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.54179791, 0.21674178, 0.94161672],
       [0.14725176, 0.72241364, 0.18508126],
       [0.74625415, 0.31126422, 0.33997451],
       [0.46889788, 0.16226261, 0.1147502 ],
       [0.0910639 , 0.49863285, 0.70529179]])

In [22]:
random_array3 = np.random.rand(5,3)
random_array3

array([[8.07856598e-01, 7.03517417e-01, 9.83061656e-01],
       [2.17092276e-01, 8.18224511e-01, 8.94620392e-01],
       [8.52741513e-01, 2.47598635e-01, 4.14404622e-01],
       [2.59015422e-04, 7.06451789e-01, 7.11561106e-01],
       [3.47597777e-01, 8.94214293e-02, 8.93862920e-02]])

In [32]:
# Pseduo Random Numbers
np.random.seed(seed=2)
random_array4 = np.random.randint(10,size=(5,3))
random_array4

array([[8, 8, 6],
       [2, 8, 7],
       [2, 1, 5],
       [4, 4, 5],
       [7, 3, 6]])

## Viewing Arrays And Matrices

In [33]:
np.unique(random_array4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a3[0][1]

array([4, 5, 6])

In [37]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

## Manipulating & Comparing arrays

In [42]:
# Arithmetic
a1 = np.array([1,2,3])
ones = np.ones(3)

In [44]:
a1 + ones 

array([2., 3., 4.])

In [45]:
a1-ones

array([0., 1., 2.])

In [46]:
a1*ones

array([1., 2., 3.])

In [48]:
a1

array([1, 2, 3])

In [49]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [51]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [53]:
a2*a3
# How to reshape a2 to be compatible with a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [54]:
a1/ones

array([1., 2., 3.])

In [55]:
a2//a1 # Floor division removes the decimals 

array([[1, 1, 1],
       [4, 2, 2]], dtype=int32)

In [56]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [57]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [58]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [59]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [60]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregations 

In [61]:

massive_array = np.random.random(100000)
massive_array[:10]


array([0.51357812, 0.18443987, 0.78533515, 0.85397529, 0.49423684,
       0.84656149, 0.07964548, 0.50524609, 0.0652865 , 0.42812233])

In [63]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # Numpy's sum()

4.82 ms ± 169 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
28.2 µs ± 1.13 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [64]:
np.mean(a2)

3.5

In [65]:
np.max(a2)

6

In [66]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.707825127659933

In [67]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = Lower range of numbers 
np.var(a2)

2.9166666666666665

### Reshaping and Transposing

In [69]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [74]:
a2*a3
# To multiply them either both should be same shape or one of them should be 1D array

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [75]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [76]:
a2_reshape * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [78]:
# transpose
a2, a2.T

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

### Dot Product

In [79]:
np.random.seed(0)

mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))

mat1,mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [80]:
mat1 * mat2 # Element wise multiplication

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [81]:
np.dot(mat1,mat2.T) # Dot product
# Condition - i*j mat can be multiplied with j*k mat

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

### Comparison Operators 

In [82]:
a1,a2

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [83]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [86]:
bool_array = a1>=a2
bool_array

array([[ True,  True,  True],
       [False, False, False]])

In [87]:
a1==a1

array([ True,  True,  True])

### Sorting Arrays

In [89]:
random_array = np.random.randint(10,size=(3,5))
random_array

array([[2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7]])

In [90]:
np.sort(random_array)

array([[1, 2, 3, 3, 8],
       [0, 1, 3, 3, 7],
       [0, 4, 7, 9, 9]])

In [91]:
np.argsort(random_array) #returns indices 

array([[3, 0, 1, 4, 2],
       [3, 4, 0, 1, 2],
       [2, 3, 4, 0, 1]], dtype=int64)

In [92]:
a1,np.argmin(a1)

(array([1, 2, 3]), 0)

In [94]:
random_array, np.argmax(random_array,axis=0)

(array([[2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1],
        [9, 9, 0, 4, 7]]),
 array([2, 2, 0, 2, 2], dtype=int64))

In [95]:
random_array, np.argmax(random_array, axis=1)

(array([[2, 3, 8, 1, 3],
        [3, 3, 7, 0, 1],
        [9, 9, 0, 4, 7]]),
 array([2, 2, 0], dtype=int64))